name: Deploy to Tencent Lighthouse

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: centos-stream-9
    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/SunSheetMusic
          git pull origin main
          npm install
          npm run build
